### PR TITLE
Re-add Warp Itemducts, Luxducts and introducing Omniducts

### PR DESCRIPTION
**Pull request by Astavie**
conversation

I'm mainly opening this pull request for the Warp Itemducts and Luxducts, but I also saw that Omniducts were a thing in the code so I added them as well.

I changed the recipe of the Warp Itemduct from 6 itemducts + 1 enderium to 6 signalum plated itemducts + 1 enderium. I did this because the Warp Itemducts can transfer 4000 RF/t, just like the signalum plated itemducts.

The recipe for the omniduct is 3 signalum itemducts + 3 signalum fluiducts + enderium ingot. They look like Warp Itemducts so I made the recipe similar to it.

### CODE REVIEW

**Comment by KingLemming** [comment]
You have changed a lot of things that don't necessarily need to be changed and you have undone some very intentional changes.

I'm not sure that I can accept this as is.

**Comment by Astavie** [comment]
And what would these things be? Like, the recipes?

**Comment by KingLemming** [comment]
Well, you readded the hardcoded NODE_TRANSFER = 4000. I very intentionally changed that so that it adjusts with config options.

Also, it looks like you've basically just readded recipes. These ducts were left out because they were a little buggy and didn't necessarily work correctly. I don't see any logic adjustments.

**Comment by Astavie** [comment]
I'm honestly not sure how the `NODE_TRANSFER = 4000` happened, it just appeared when I merged into the dev branch. I'll change it back.

Also, as far as I could see the ducts worked fine. Well, the warp duct just deleted items but that was solved with a simple ItemStack:copy

**Comment by KingLemming** [comment]
And...you didn't think that maybe the copy() is kind of a kludgey solution? There's maybe some other underlying logic problems there.

**Comment by Astavie** [comment]
The problem was that the item would be sent, and that the same itemstack instance would be present in both chests. So when the item was removed from the first because it was extracted (done with setCount(0)), it was also removed from the second. Ergo, the stack should be copied.

**Comment by Astavie** [comment]
I suppose splitStack would be a bit neater, but that is something that needs to be edited in net.minecraftforge.items.ItemHandlerHelper#insertItem

**Comment by LordMZTE** [comment]
I really miss the warp itemducts
especially how well they worked with the logistics pipes mod (which is sadly abandoned)

**Comment by KingLemming** [comment]
Yeah...I'm sorry, but I'm going to have to ask that you resubmit this as separate PRs to readd each individual feature.

As is, here's how it's going to (probably) go down.

I merge it, then there will be a bug, and frankly I'm not gonna have time to track down whatever it is, so I have to revert *all* of it and nothing gets added.

**Comment by KingLemming** [comment]
Basically, when I made the comment about PRing in the Discord, I meant some well-tested and provable PRs.

A *lot* of this is just uncommenting code, and that code was commented out for a reason.

**Comment by Astavie** [comment]
Alright. Do you know why these were removed? Or do I have to test until something explodes :p

**Comment by KingLemming** [comment]
You'll need to test. I don't remember exactly what the issues were.

**Pull request closed without merging**
