### PR TITLE
[1.12] Allow addons to create custom attachments

### PR DESCRIPTION
**Pull request by Astavie**
I changed the id system of attachments to be based off ResourceLocation (like TileEntity) instead of byte. This will allow addon creators to create additional attachments.

This should fix CoFH/Feedback#561

### CODE REVIEW

**Comment by KingLemming** [comment]
Interesting.

**Comment by Drullkus** [comment]
Whoa 👀

**Comment by Astavie** [comment]
This latest commit removes code checking for specific attachments (e.g. the retrievers checking for themselves) to allow thermal dynamic's attachments to work with potential new ones.

AFAIK this pull request shouldn't change how the current attachments function.

**Comment by KingLemming** [comment]
I believe you, but we definitely have to do some testing to make sure that's the case. :)

**Comment by covers1624** [comment]
Looks good, one major issue still stands, this will crash existing worlds, as you change data type from int to string. Also, you will need some sort of migration to load the int based id's to the new ResourceLocations.

**Comment by Astavie** [comment]
That should do it, I think

**Review by covers1624 — APPROVED** [review]

**Comment by covers1624** [comment]
Yep, looks good. This should hold up nicely until TD3.

**Comment by covers1624** [comment]
Oh, actually can you change the base of this to the dev branch please?

**Comment by Astavie** [comment]
Sure thing :)

**Comment by KingLemming** [comment]
Alright, let's give this a spin.

**Pull request merged**
